#!/usr/bin/expect -f

spawn make
wait
spawn fe/fe -f ../materials/challenge.bin
set pid [exp_pid]
set fe $spawn_id

send "take tablet\r"
send "use tablet\r"
send "south\r"
send "north\r"
send "doorway\r"
send "north\r"
send "north\r"
send "bridge\r"
send "continue\r"
send "down\r"
send "east\r"
send "take empty lantern\r"
send "west\r"
send "west\r"
send "passage\r"
send "ladder\r"
send "west\r"
send "south\r"
send "north\r"
send "take can\r"
send "use can\r"
send "west\r"
send "use lantern\r"
send "east\r"
send "east\r"
send "north\r"
send "south\r"
send "west\r"
send "north\r"
send "north\r"
send "ladder\r"
send "darkness\r"
send "continue\r"
send "west\r"
send "west\r"
send "west\r"
send "west\r"
send "north\r"
send "take red coin\r"
send "north\r"
send "east\r"
send "take concave coin\r"
send "down\r"
send "take corroded coin\r"
send "up\r"
send "west\r"
send "west\r"
send "take blue coin\r"
send "up\r"
send "take shiny coin\r"
send "down\r"
send "east\r"
send "use blue coin\r"
send "use red coin\r"
send "use shiny coin\r"
send "use concave coin\r"
send "use corroded coin\r"
send "look\r"
send "north\r"
send "take teleporter\r"
send "use teleporter\r"
send "take business card\r"
expect "Synacor Headquarters"
send "take strange book\r"
send "look strange book\r"
spawn kill -USR2 $pid
wait
set spawn_id $fe
expect "Override"
send "use teleporter\r"
expect "?"
send "\r"
interact

